spring:
  application:
    name: grpcauth
  authentication:
    project_id: ${PROJECT_ID:grpc-identity-platform-test}
    issuer_uri: ${ISSUER_URI:https://securetoken.google.com/}
  grpc:
    server:
      reflection:
        enabled: ${GRPC_REFLECTION_ENABLED:false}
      health:
      enabled: true